on:
  workflow_call:
    inputs:
      release-tag-name:
        required: true
        type: string
      push:
        required: true
        type: boolean
      release:
        required: false
        default: false
        type: boolean

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run dapper
        run: make ci

      # - name: Read some Secrets
      #   uses: rancher-eio/read-vault-secrets@main
      #   if: ${{ inputs.push == true }}
      #   with:
      #     secrets: |
      #       secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
      #       secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   if: ${{ inputs.push == true }}
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ env.DOCKER_PASSWORD }}

      # - name: Docker Build
      #   uses: docker/build-push-action@v5
      #   with:
      #     provenance: false
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     file: package/Dockerfile
      #     push: ${{ inputs.push }}
      #     tags: rancher/support-bundle-kit:${{ inputs.release-tag-name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && ${{ fromJson(inputs.release) == true }}
        with:
          files: |
            dist/artifacts/support-bundle-kit-amd64
            dist/artifacts/support-bundle-kit-arm64
            dist/artifacts/sha256sum-amd64.txt
            dist/artifacts/sha256sum-arm64.txt
